[package]
name = "rust-android-example"
version = "0.1.0"
authors = ["Philipp Kaiser"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
glutin = "0.24.1"
winit = "0.22.2"
takeable-option = "0.4"

[build-dependencies]
gl_generator = "0.14.0"

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.1"

[patch.crates-io]
ndk-sys = { git = "https://github.com/rust-windowing/android-ndk-rs" }
ndk = { git = "https://github.com/rust-windowing/android-ndk-rs" }
ndk-glue = { git = "https://github.com/rust-windowing/android-ndk-rs" }
glutin = { git = "https://github.com/Kaiser1989/glutin" }
winit = { git = "https://github.com/Kaiser1989/winit" }


[package.metadata.android]
build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android" ]
